# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Kursach\Interfaces\UI\AdminWindows\AdminWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 405)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 631, 481))
        self.label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.0201244, y1:0.96, x2:1, y2:0, stop:0.0746269 rgba(74, 74, 74, 255), stop:0.950249 rgba(197, 197, 197, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.toEditNotaryWindow = QtWidgets.QPushButton(self.centralwidget)
        self.toEditNotaryWindow.setGeometry(QtCore.QRect(80, 240, 321, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toEditNotaryWindow.setFont(font)
        self.toEditNotaryWindow.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.toEditNotaryWindow.setObjectName("toEditNotaryWindow")
        self.toAuthWindow = QtWidgets.QPushButton(self.centralwidget)
        self.toAuthWindow.setGeometry(QtCore.QRect(80, 310, 321, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toAuthWindow.setFont(font)
        self.toAuthWindow.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.toAuthWindow.setObjectName("toAuthWindow")
        self.toClientsViewWindow = QtWidgets.QPushButton(self.centralwidget)
        self.toClientsViewWindow.setGeometry(QtCore.QRect(80, 170, 321, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toClientsViewWindow.setFont(font)
        self.toClientsViewWindow.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.toClientsViewWindow.setObjectName("toClientsViewWindow")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(38, 18, 148);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(38, 18, 148);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toEditNotaryWindow.setText(_translate("MainWindow", "РЕДАКТИРОВАТЬ НОТАРИУСОВ"))
        self.toAuthWindow.setText(_translate("MainWindow", "ВЫХОД"))
        self.toClientsViewWindow.setText(_translate("MainWindow", "ПРОСМОТРЕТЬ СПИСОК КЛИЕНТОВ"))
        self.label_2.setText(_translate("MainWindow", "Добро пожаловать в систему, username!"))
        self.label_3.setText(_translate("MainWindow", "Выберите действие"))
