# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Kursach\Interfaces\UI\ClientWindows\ClientWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientWindow(object):
    def setupUi(self, ClientWindow):
        ClientWindow.setObjectName("ClientWindow")
        ClientWindow.resize(517, 466)
        self.centralwidget = QtWidgets.QWidget(ClientWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 631, 481))
        self.label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.0201244, y1:0.96, x2:1, y2:0, stop:0.0746269 rgba(74, 74, 74, 255), stop:0.950249 rgba(197, 197, 197, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.completedDealsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.completedDealsBtn.setGeometry(QtCore.QRect(130, 220, 281, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.completedDealsBtn.setFont(font)
        self.completedDealsBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.completedDealsBtn.setObjectName("completedDealsBtn")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(130, 340, 281, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exitBtn.setFont(font)
        self.exitBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.exitBtn.setObjectName("exitBtn")
        self.makeDealBtn = QtWidgets.QPushButton(self.centralwidget)
        self.makeDealBtn.setGeometry(QtCore.QRect(130, 160, 281, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.makeDealBtn.setFont(font)
        self.makeDealBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.makeDealBtn.setObjectName("makeDealBtn")
        self.welcome = QtWidgets.QLabel(self.centralwidget)
        self.welcome.setGeometry(QtCore.QRect(80, 50, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.welcome.setFont(font)
        self.welcome.setStyleSheet("color: rgb(38, 18, 148);")
        self.welcome.setObjectName("welcome")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(38, 18, 148);")
        self.label_3.setObjectName("label_3")
        self.profileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.profileBtn.setGeometry(QtCore.QRect(130, 280, 281, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.profileBtn.setFont(font)
        self.profileBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.profileBtn.setObjectName("profileBtn")
        ClientWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ClientWindow)
        QtCore.QMetaObject.connectSlotsByName(ClientWindow)

    def retranslateUi(self, ClientWindow):
        _translate = QtCore.QCoreApplication.translate
        ClientWindow.setWindowTitle(_translate("ClientWindow", "MainWindow"))
        self.completedDealsBtn.setText(_translate("ClientWindow", "СОВЕРШЁННЫЕ СДЕЛКИ"))
        self.exitBtn.setText(_translate("ClientWindow", "ВЫХОД"))
        self.makeDealBtn.setText(_translate("ClientWindow", "ЗАКЛЮЧИТЬ СДЕЛКУ"))
        self.welcome.setText(_translate("ClientWindow", "Добро пожаловать в систему, username!"))
        self.label_3.setText(_translate("ClientWindow", "Выберите действие"))
        self.profileBtn.setText(_translate("ClientWindow", "ПРОФИЛЬ"))
