# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Kursach\Interfaces\UI\ClientWindows\ConfirmDealWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmDealWindow(object):
    def setupUi(self, ConfirmDealWindow):
        ConfirmDealWindow.setObjectName("ConfirmDealWindow")
        ConfirmDealWindow.resize(805, 542)
        self.centralwidget = QtWidgets.QWidget(ConfirmDealWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 811, 591))
        self.label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.0201244, y1:0.96, x2:1, y2:0, stop:0.0746269 rgba(74, 74, 74, 255), stop:0.950249 rgba(197, 197, 197, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.aboutOffer = QtWidgets.QTextEdit(self.centralwidget)
        self.aboutOffer.setGeometry(QtCore.QRect(23, 46, 761, 421))
        self.aboutOffer.setStyleSheet("border-radius: 10px;\n"
"background: white;")
        self.aboutOffer.setReadOnly(True)
        self.aboutOffer.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.aboutOffer.setObjectName("aboutOffer")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 20, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(32, 34, 156);")
        self.label_2.setObjectName("label_2")
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setGeometry(QtCore.QRect(630, 480, 151, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.cancelBtn.setObjectName("cancelBtn")
        self.confirmBtn = QtWidgets.QPushButton(self.centralwidget)
        self.confirmBtn.setGeometry(QtCore.QRect(300, 480, 211, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.confirmBtn.setFont(font)
        self.confirmBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.confirmBtn.setObjectName("confirmBtn")
        self.downloadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.downloadBtn.setGeometry(QtCore.QRect(30, 480, 151, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.downloadBtn.setFont(font)
        self.downloadBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.downloadBtn.setObjectName("downloadBtn")
        ConfirmDealWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConfirmDealWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfirmDealWindow)

    def retranslateUi(self, ConfirmDealWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfirmDealWindow.setWindowTitle(_translate("ConfirmDealWindow", "MainWindow"))
        self.aboutOffer.setHtml(_translate("ConfirmDealWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Данный документ подтверждает совершение сделки. Ниже перечислены подробные сведения о сделке. Пожалуйста, прежде чем приступать к оформлению сделки ознакомьтесь с данным документом! После подтверждения сделки она вступает в силу и её отмена невозможна. В случае каких-либо проблем с любыми вопросами обращаться к нотариусу с которым была заключена сделка. Подробные сведения:</span></p></body></html>"))
        self.label_2.setText(_translate("ConfirmDealWindow", "Документ о сделке"))
        self.cancelBtn.setText(_translate("ConfirmDealWindow", "Отменить сделку"))
        self.confirmBtn.setText(_translate("ConfirmDealWindow", "Подтвердить"))
        self.downloadBtn.setText(_translate("ConfirmDealWindow", "Скачать документ"))
