# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Kursach\Interfaces\UI\NotaryWindows\DealAddWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DealAddWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 461)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -15, 711, 511))
        self.label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.0201244, y1:0.96, x2:1, y2:0, stop:0.0746269 rgba(74, 74, 74, 255), stop:0.950249 rgba(197, 197, 197, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.dealName = QtWidgets.QLineEdit(self.centralwidget)
        self.dealName.setGeometry(QtCore.QRect(40, 30, 221, 31))
        self.dealName.setStyleSheet("border-radius: 10px;")
        self.dealName.setObjectName("dealName")
        self.dealPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.dealPrice.setValidator(QtGui.QIntValidator())
        self.dealPrice.setMaxLength(5)
        self.dealPrice.setGeometry(QtCore.QRect(390, 30, 131, 31))
        self.dealPrice.setStyleSheet("border-radius: 10px;")
        self.dealPrice.setObjectName("dealPrice")
        self.dealDescr = QtWidgets.QTextEdit(self.centralwidget)
        self.dealDescr.setGeometry(QtCore.QRect(40, 80, 481, 311))
        self.dealDescr.setStyleSheet("border-radius: 10px;\n"
"background: white;")
        self.dealDescr.setObjectName("dealDescr")
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setGeometry(QtCore.QRect(380, 400, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.cancelBtn.setObjectName("cancelBtn")
        self.addDealBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addDealBtn.setGeometry(QtCore.QRect(40, 400, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addDealBtn.setFont(font)
        self.addDealBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.addDealBtn.setObjectName("addDealBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dealName.setPlaceholderText(_translate("MainWindow", "Введите название услуги.."))
        self.dealPrice.setPlaceholderText(_translate("MainWindow", "Введите цену.."))
        self.dealDescr.setPlaceholderText(_translate("MainWindow", "Введите описание.."))
        self.cancelBtn.setText(_translate("MainWindow", "НАЗАД"))
        self.addDealBtn.setText(_translate("MainWindow", "ДОБАВИТЬ"))
