# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Kursach\Interfaces\UI\NotaryWindows\NotaryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotaryWindow(object):
    def setupUi(self, NotaryWindow):
        NotaryWindow.setObjectName("NotaryWindow")
        NotaryWindow.resize(479, 426)
        self.centralwidget = QtWidgets.QWidget(NotaryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 631, 491))
        self.label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.0201244, y1:0.96, x2:1, y2:0, stop:0.0746269 rgba(74, 74, 74, 255), stop:0.950249 rgba(197, 197, 197, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.editDealBtn = QtWidgets.QPushButton(self.centralwidget)
        self.editDealBtn.setGeometry(QtCore.QRect(110, 220, 281, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.editDealBtn.setFont(font)
        self.editDealBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.editDealBtn.setObjectName("editDealBtn")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(110, 340, 281, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exitBtn.setFont(font)
        self.exitBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.exitBtn.setObjectName("exitBtn")
        self.clientListBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clientListBtn.setGeometry(QtCore.QRect(110, 160, 281, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clientListBtn.setFont(font)
        self.clientListBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.clientListBtn.setObjectName("clientListBtn")
        self.welcome = QtWidgets.QLabel(self.centralwidget)
        self.welcome.setGeometry(QtCore.QRect(70, 50, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.welcome.setFont(font)
        self.welcome.setStyleSheet("color: rgb(38, 18, 148);")
        self.welcome.setObjectName("welcome")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(38, 18, 148);")
        self.label_3.setObjectName("label_3")
        self.toProfileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.toProfileBtn.setGeometry(QtCore.QRect(110, 280, 281, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toProfileBtn.setFont(font)
        self.toProfileBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.toProfileBtn.setObjectName("toProfileBtn")
        NotaryWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(NotaryWindow)
        QtCore.QMetaObject.connectSlotsByName(NotaryWindow)

    def retranslateUi(self, NotaryWindow):
        _translate = QtCore.QCoreApplication.translate
        NotaryWindow.setWindowTitle(_translate("NotaryWindow", "MainWindow"))
        self.editDealBtn.setText(_translate("NotaryWindow", "РЕДАКТИРОВАТЬ УСЛУГИ"))
        self.exitBtn.setText(_translate("NotaryWindow", "ВЫХОД"))
        self.clientListBtn.setText(_translate("NotaryWindow", "ПРОСМОТРЕТЬ СПИСОК КЛИЕНТОВ"))
        self.welcome.setText(_translate("NotaryWindow", "Добро пожаловать в систему, username!"))
        self.label_3.setText(_translate("NotaryWindow", "Выберите действие"))
        self.toProfileBtn.setText(_translate("NotaryWindow", "ПРОФИЛЬ"))
