# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Kursach\Interfaces\UI\AuthWindows\registrWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrWindow(object):
    def setupUi(self, RegistrWindow):
        RegistrWindow.setObjectName("RegistrWindow")
        RegistrWindow.resize(433, 430)
        self.centralwidget = QtWidgets.QWidget(RegistrWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 561, 481))
        self.label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.0201244, y1:0.96, x2:1, y2:0, stop:0.0746269 rgba(74, 74, 74, 255), stop:0.950249 rgba(197, 197, 197, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.registrBtn = QtWidgets.QPushButton(self.centralwidget)
        self.registrBtn.setGeometry(QtCore.QRect(130, 300, 171, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.registrBtn.setFont(font)
        self.registrBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.registrBtn.setObjectName("registrBtn")
        self.initialsEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.initialsEdit.setGeometry(QtCore.QRect(90, 90, 291, 31))
        self.initialsEdit.setStyleSheet("border-radius: 10px;")
        self.initialsEdit.setObjectName("initialsEdit")
        self.logEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.logEdit.setGeometry(QtCore.QRect(90, 140, 291, 31))
        self.logEdit.setStyleSheet("border-radius: 10px;")
        self.logEdit.setObjectName("logEdit")
        self.passEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passEdit.setGeometry(QtCore.QRect(90, 240, 291, 31))
        self.passEdit.setStyleSheet("border-radius: 10px;")
        self.passEdit.setMaxLength(32767)
        self.passEdit.setObjectName("passEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/user_customer_man_14016.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 240, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/cslogin_104358.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 140, 31, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/message_12953390.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setGeometry(QtCore.QRect(160, 350, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setStyleSheet("border-color: rgb(255, 249, 62);\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 192, 66);\n"
"border: 1px solid #000000")
        self.cancelBtn.setObjectName("cancelBtn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 40, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(11, 29, 148);")
        self.label_5.setObjectName("label_5")
        self.numberEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.numberEdit.setGeometry(QtCore.QRect(90, 190, 291, 31))
        self.numberEdit.setStyleSheet("border-radius: 10px;")
        #self.numberEdit.setValidator(QtGui.QIntValidator())
        #self.numberEdit.setMaxLength(120)
        self.numberEdit.setObjectName("numberEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 190, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/calling_12550156.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.passLine = QtWidgets.QLabel(self.centralwidget)
        self.passLine.setGeometry(QtCore.QRect(90, 271, 331, 20))
        self.passLine.setStyleSheet("color: rgb(11, 29, 148);")
        self.passLine.setText("")
        self.passLine.setObjectName("passLine")
        self.logLine = QtWidgets.QLabel(self.centralwidget)
        self.logLine.setGeometry(QtCore.QRect(50, 170, 371, 21))
        self.logLine.setStyleSheet("color: rgb(11, 29, 148);")
        self.logLine.setText("")
        self.logLine.setObjectName("logLine")
        self.numberLine = QtWidgets.QLabel(self.centralwidget)
        self.numberLine.setGeometry(QtCore.QRect(90, 220, 321, 16))
        self.numberLine.setStyleSheet("color: rgb(11, 29, 148);")
        self.numberLine.setText("")
        self.numberLine.setObjectName("numberLine")
        self.initialsLine = QtWidgets.QLabel(self.centralwidget)
        self.initialsLine.setGeometry(QtCore.QRect(100, 120, 331, 20))
        self.initialsLine.setStyleSheet("color: rgb(11, 29, 148);")
        self.initialsLine.setText("")
        self.initialsLine.setObjectName("initialsLine")
        RegistrWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegistrWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrWindow)

    def retranslateUi(self, RegistrWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrWindow.setWindowTitle(_translate("RegistrWindow", "MainWindow"))
        self.registrBtn.setText(_translate("RegistrWindow", "РЕГИСТРАЦИЯ"))
        self.initialsEdit.setPlaceholderText(_translate("RegistrWindow", "Введите Ф.И.О"))
        self.logEdit.setPlaceholderText(_translate("RegistrWindow", "Введите логин"))
        self.passEdit.setPlaceholderText(_translate("RegistrWindow", "Введите пароль"))
        self.cancelBtn.setText(_translate("RegistrWindow", "ОТМЕНА"))
        self.label_5.setText(_translate("RegistrWindow", "Введите данные"))
        self.numberEdit.setPlaceholderText(_translate("RegistrWindow", "Введите номер телефона"))

